services:
  redisapi:
    build: .
    container_name: redisapi
    image: redisapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # کانکشن‌استرینگ را اینجا Override کن
      - ConnectionStrings__Redis=sentinel1:26379,sentinel2:26379,sentinel3:26379,serviceName=mymaster,abortConnect=false,ssl=False,defaultDatabase=0,password=1234@!@#$,connectTimeout=5000,syncTimeout=5000,tieBreaker=
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - swarm-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      mode: replicated

networks:
  swarm-network:
    external: true